#!/usr/bin/env python3
"""Deterministic mobile fixture-sync verifier for hermes-mobile.

Verifies that the fixture files copied under
app/src/test/resources/fixtures/ are byte-identical to the pinned
asgard-rooms oracle fixtures, and regenerates the mobile pin manifest
(app/src/test/resources/fixtures/fixture-set.sha256) from:

  1. the upstream asgard-rooms fixture-set.sha256 lines for the selected
     copied artifacts, and
  2. the source commit recorded in tools/roomfixtures/sync-info.json,

so the manifest is derived, never hand-typed.

Modes:
  check   verify copied fixtures + committed manifest byte-for-byte (CI gate)
  write   regenerate the manifest (run only right after a sync)

Exit status: 0 ok, 1 drift/mismatch. Deterministic: no network, no time,
no environment input — only repo bytes.
"""
import hashlib
import json
import os
import sys

# hermes-mobile repo root (tools/roomfixtures/ -> up 3)
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
FIX = os.path.join(ROOT, "app", "src", "test", "resources", "fixtures")
SYNC_INFO = os.path.join(ROOT, "tools", "roomfixtures", "sync-info.json")

# The upstream files mirrored into the mobile fixture dir. GATEWAY-SIZE-EVIDENCE.json
# is a generated evidence artifact (not a parser fixture) but is mirrored and pinned
# so the estimator assertions run against a pinned, source-derived file.
# Listed explicitly; new upstream files are NOT auto-copied.
COPIED_FILES = [
    "EXPECTED-cache-walk.json",
    "EXPECTED.json",
    "GATEWAY-SIZE-EVIDENCE.json",
    "at-normalization.json",
    "legacy-name-key.json",
    "legacy-v1.json",
    "legacy-v2.json",
    "v3-capped-room-evicted/02-before.json",
    "v3-capped-room-evicted/03-after.json",
    "v3-capped-room-evicted/04-gamma-returns.json",
    "v3-malformed.json",
    "v3-normal.json",
]

UPSTREAM_MARKER = "# upstream: HaeinGeek/asgard-rooms"


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def read_sync_info():
    with open(SYNC_INFO, "r", encoding="utf-8") as f:
        info = json.load(f)
    for key in ("repo", "commit", "fixture_set_sha256"):
        if not isinstance(info.get(key), str) or not info[key]:
            raise SystemExit(f"sync-info.json: missing field {key!r}")
    return info


def load_upstream_pin(info):
    """Parse the embedded upstream fixture-set.sha256 content into {name: hash}."""
    pins = {}
    for line in info["fixture_set_sha256"].splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split(None, 1)
        if len(parts) != 2:
            raise SystemExit(f"sync-info.json: unparseable upstream pin line: {line!r}")
        pins[parts[1].strip()] = parts[0]
    return pins


def expected_manifest(info):
    """Deterministically derive the manifest text from upstream pin + commit."""
    lines = [
        f"{UPSTREAM_MARKER} @{info['commit']}",
        "# Generated by tools/roomfixtures/verify_fixture_sync.py (write mode).",
        "# Do not edit by hand: regenerate after syncing from the reviewed upstream head.",
    ]
    for name in COPIED_FILES:
        lines.append(f"{load_upstream_pin(info)[name]}  {name}")
    return "\n".join(lines) + "\n"


def check():
    problems = []
    info = read_sync_info()
    upstream = load_upstream_pin(info)

    missing_upstream = [n for n in COPIED_FILES if n not in upstream]
    if missing_upstream:
        problems.append(f"upstream pin lacks copied file(s): {missing_upstream}")

    # 1. every copied fixture must be byte-identical to the upstream pin
    for name in COPIED_FILES:
        path = os.path.join(FIX, name)
        if not os.path.isfile(path):
            problems.append(f"copied fixture missing: {name}")
            continue
        got = sha256(path)
        want = upstream.get(name)
        if want and got != want:
            problems.append(f"fixture '{name}' drifted from upstream pin {info['commit']}:\n  pin:    {want}\n  actual: {got}")

    # 2. the committed manifest must equal the deterministic derivation
    manifest_path = os.path.join(FIX, "fixture-set.sha256")
    if not os.path.isfile(manifest_path):
        problems.append("fixture-set.sha256 missing")
    else:
        committed = open(manifest_path, "r", encoding="utf-8").read()
        derived = expected_manifest(info)
        if committed != derived:
            problems.append(
                "committed fixture-set.sha256 does not match the deterministic derivation\n"
                "  (upstream pin + source commit). Regenerate with:\n"
                "  python3 tools/roomfixtures/verify_fixture_sync.py write"
            )

    if problems:
        print("fixture sync check FAILED:")
        for p in problems:
            print("  -", p)
        return 1
    print(
        f"fixture sync verified: {len(COPIED_FILES)} files byte-identical to "
        f"{info['repo']}@{info['commit'][:12]}; manifest matches its deterministic derivation"
    )
    return 0


def write():
    info = read_sync_info()
    # refuse to write a manifest that would vouch for drifted files
    upstream = load_upstream_pin(info)
    for name in COPIED_FILES:
        path = os.path.join(FIX, name)
        if not os.path.isfile(path):
            raise SystemExit(f"copied fixture missing: {name}")
        got = sha256(path)
        want = upstream.get(name)
        if want and got != want:
            raise SystemExit(
                f"refusing to regenerate: fixture '{name}' is not byte-identical to the "
                f"upstream pin ({info['commit']}). Copy the file first."
            )
    out = os.path.join(FIX, "fixture-set.sha256")
    with open(out, "w", encoding="utf-8") as f:
        f.write(expected_manifest(info))
    print(f"wrote {os.path.relpath(out, ROOT)} ({len(COPIED_FILES)} files, derived from upstream pin @ {info['commit'][:12]})")
    return 0


if __name__ == "__main__":
    mode = sys.argv[1] if len(sys.argv) > 1 else "check"
    if mode == "check":
        sys.exit(check())
    if mode == "write":
        sys.exit(write())
    print(f"usage: {sys.argv[0]} [check|write]", file=sys.stderr)
    sys.exit(2)
